[phases.setup]
nixPkgs = [
    "nodejs_20",
    "nodejs-20_x",
    "nodePackages.npm",
    "postgresql"
]

[phases.install]
cmds = [
    "npm install"
]

[phases.build]
cmds = [
    "npm run prisma:generate"
]

[start]
cmd = "npm start"
